workflows:
  ios-syra-simulator:
    name: SYRA iOS Native (Simulator)
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Build (simulator)
        script: |
          set -euo pipefail
          cd ios_native
          xcodebuild \
            -project SyraNative.xcodeproj \
            -scheme SyraNative \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath "$CM_BUILD_DIR/DerivedData" \
            clean build
    artifacts:
      - $CM_BUILD_DIR/DerivedData/Build/Products/Release-iphonesimulator/*.app
      - $CM_BUILD_DIR/DerivedData/Logs/Build/*.xcactivitylog

  ios-syra-testflight:
    name: SYRA iOS Native (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: SyraAPIKey

    environment:
      xcode: latest

      # ✅ iOS tarafında reference name’i tek tek yazmak yerine
      # Codemagic bu iki bilgiyle "eşleşen" certificate + profile’ları otomatik çeker. :contentReference[oaicite:3]{index=3}
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ariksoftware.syra

      vars:
        TEAM_ID: 4NK7SA2722
        XCODE_SCHEME: "SyraNative"

    scripts:
      - name: Install Codemagic CLI tools
        script: |
          set -euo pipefail
          pip3 install codemagic-cli-tools -q || true

      - name: Apply provisioning profiles to Xcode project
        script: |
          set -euo pipefail
          cd ios_native
          xcode-project use-profiles

      - name: Set build number (CFBundleVersion)
        script: |
          set -euo pipefail
          cd ios_native
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $CM_BUILD_NUMBER" Info.plist \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $CM_BUILD_NUMBER" Info.plist

      - name: Archive (Release)
        script: |
          set -euo pipefail
          cd ios_native

          xcodebuild \
            -project SyraNative.xcodeproj \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath "$CM_BUILD_DIR/SyraNative.xcarchive" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            clean archive | xcpretty

      - name: Export IPA (App Store)
        script: |
          set -euo pipefail

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/SyraNative.xcarchive" \
            -exportPath "$CM_BUILD_DIR/export" \
            -exportOptionsPlist "ios_native/ExportOptions_AppStore.plist" \
            | xcpretty

          ls -la "$CM_BUILD_DIR/export/" || true

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/export/*.dSYM.zip
      - $CM_BUILD_DIR/SyraNative.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
