workflows:
  ios-syra-simulator:
    name: SYRA iOS Native (Simulator)
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Build (simulator)
        script: |
          set -euo pipefail
          cd ios_native
          xcodebuild \
            -project SyraNative.xcodeproj \
            -scheme SyraNative \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath "$CM_BUILD_DIR/DerivedData" \
            clean build
    artifacts:
      - $CM_BUILD_DIR/DerivedData/Build/Products/Release-iphonesimulator/*.app
      - $CM_BUILD_DIR/DerivedData/Logs/Build/*.xcactivitylog

  ios-syra-testflight:
    name: SYRA iOS Native (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: SyraAPIKey

    environment:
      xcode: latest

      ios_signing:
        certificates:
          - syra_appstore_dist_2025_12_13
        provisioning_profiles:
          - syra_appstore_profile

      vars:
        TEAM_ID: 4NK7SA2722
        BUNDLE_ID: com.ariksoftware.syra
        MARKETING_VERSION: "1.0.4"

    scripts:
      - name: Install tools (codemagic-cli-tools + xcpretty)
        script: |
          set -euo pipefail
          pip3 install codemagic-cli-tools -q || true
          sudo gem install xcpretty -N || true

      - name: Verify signing identities + apply profiles
        script: |
          set -euo pipefail
          echo "🔎 Code signing identities in keychain:"
          security find-identity -v -p codesigning || true

          echo "🧩 Applying provisioning profiles to Xcode project..."
          cd ios_native
          xcode-project use-profiles

          echo "📱 Installed provisioning profiles:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ || true

      - name: Sync Info.plist version + build (force)
        script: |
          set -euo pipefail
          cd ios_native

          BUILD_NUM="${CM_BUILD_NUMBER:-${BUILD_NUMBER:-${CM_BUILD_ID:-$(date +%s)}}}"
          echo "✅ Will publish version: $MARKETING_VERSION"
          echo "✅ Will publish build:   $BUILD_NUM"

          # ✅ Sabit plist yolu (senin repoda var)
          PLIST_PATH="Info.plist"

          if [ ! -f "$PLIST_PATH" ]; then
            echo "❌ Info.plist not found at: $PLIST_PATH"
            ls -la
            exit 1
          fi

          echo "🧾 Using Info.plist: $PLIST_PATH"

          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $MARKETING_VERSION" "$PLIST_PATH" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $MARKETING_VERSION" "$PLIST_PATH"

          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUM" "$PLIST_PATH" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD_NUM" "$PLIST_PATH"

          # ✅ ikon zorunlu (AppIcon asset name)
          /usr/libexec/PlistBuddy -c "Set :CFBundleIconName AppIcon" "$PLIST_PATH" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleIconName string AppIcon" "$PLIST_PATH"

          echo "✅ Final plist values:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST_PATH" || true
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST_PATH" || true
          /usr/libexec/PlistBuddy -c "Print :CFBundleIconName" "$PLIST_PATH" || true

      - name: Archive (Release)
        script: |
          set -euo pipefail
          cd ios_native

          BUILD_NUM="${CM_BUILD_NUMBER:-${BUILD_NUMBER:-${CM_BUILD_ID:-$(date +%s)}}}"

          echo "🔨 Archiving for TestFlight..."
          echo "Bundle ID: $BUNDLE_ID"
          echo "Team ID: $TEAM_ID"
          echo "✅ Build number: $BUILD_NUM"
          echo "✅ Marketing version: $MARKETING_VERSION"

          xcodebuild \
            -project SyraNative.xcodeproj \
            -scheme SyraNative \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath "$CM_BUILD_DIR/SyraNative.xcarchive" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CURRENT_PROJECT_VERSION="$BUILD_NUM" \
            MARKETING_VERSION="$MARKETING_VERSION" \
            ASSETCATALOG_COMPILER_APPICON_NAME="AppIcon" \
            clean archive \
            | tee "$CM_BUILD_DIR/archive.log"

          echo "================= LAST 200 LINES ================="
          tail -n 200 "$CM_BUILD_DIR/archive.log" || true

          if [ ! -d "$CM_BUILD_DIR/SyraNative.xcarchive" ]; then
            echo "❌ Archive not found!"
            exit 1
          fi
          echo "✅ Archive created: $CM_BUILD_DIR/SyraNative.xcarchive"

      - name: Export IPA (App Store Connect)
        script: |
          set -euo pipefail
          echo "📦 Exporting IPA..."

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/SyraNative.xcarchive" \
            -exportPath "$CM_BUILD_DIR/export" \
            -exportOptionsPlist "ios_native/ExportOptions_AppStore.plist" \
            | xcpretty

          echo "📦 Export folder contents:"
          ls -la "$CM_BUILD_DIR/export/" || true

          IPA_PATH="$(ls -1 "$CM_BUILD_DIR/export/"*.ipa 2>/dev/null | head -n 1 || true)"
          if [ -z "$IPA_PATH" ]; then
            echo "❌ IPA export failed (no .ipa found)"
            exit 1
          fi

          echo "✅ IPA exported: $IPA_PATH"
          ls -lh "$IPA_PATH"

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/export/*.dSYM.zip
      - $CM_BUILD_DIR/SyraNative.xcarchive
      - $CM_BUILD_DIR/archive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
