workflows:
  ios-syra-testflight:
    name: SYRA iOS Native (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: SyraAPIKey

    environment:
      xcode: latest
      vars:
        TEAM_ID: 4NK7SA2722
        BUNDLE_ID: com.ariksoftware.syra
        XCODE_PROJECT: "ios_native/SyraNative.xcodeproj"
        XCODE_SCHEME: "SyraNative"

    scripts:
      - name: Install Codemagic CLI tools
        script: |
          set -euo pipefail
          pip3 install codemagic-cli-tools -q || true

      - name: Fetch signing files + apply profiles
        script: |
          set -euo pipefail

          echo "ðŸ” Initializing keychain..."
          keychain initialize

          echo "ðŸ“¥ Fetching App Store signing files for: $BUNDLE_ID"
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

          echo "ðŸ§© Applying profiles to the correct Xcode project..."
          xcode-project use-profiles --project "$XCODE_PROJECT"

          echo "ðŸ“± Installed provisioning profiles:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ || true

      - name: Set build number (CFBundleVersion)
        script: |
          set -euo pipefail
          cd ios_native
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $CM_BUILD_NUMBER" Info.plist \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $CM_BUILD_NUMBER" Info.plist

      - name: Archive (Release)
        script: |
          set -euo pipefail

          echo "ðŸ”¨ Archiving for TestFlight..."
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath "$CM_BUILD_DIR/SyraNative.xcarchive" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates \
            clean archive | xcpretty

          test -d "$CM_BUILD_DIR/SyraNative.xcarchive"

      - name: Export IPA (App Store)
        script: |
          set -euo pipefail
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/SyraNative.xcarchive" \
            -exportPath "$CM_BUILD_DIR/export" \
            -exportOptionsPlist "ios_native/ExportOptions_AppStore.plist" \
            -allowProvisioningUpdates | xcpretty

          ls -la "$CM_BUILD_DIR/export/" || true
          test -n "$(ls -1 "$CM_BUILD_DIR/export/"*.ipa 2>/dev/null | head -n 1)"

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/export/*.dSYM.zip
      - $CM_BUILD_DIR/SyraNative.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
