// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC350Jvbji5Q5-nihjNS9hB4pgQq3loP_0',
    appId: '1:843652590816:web:1034e85fb3096dafb67485',
    messagingSenderId: '843652590816',
    projectId: 'flortiq-v2',
    authDomain: 'flortiq-v2.firebaseapp.com',
    storageBucket: 'flortiq-v2.firebasestorage.app',
    measurementId: 'G-5NVVDSTLL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNuVgSAu0NO7QjgQoMpdsAigjLHnrr7WM',
    appId: '1:843652590816:android:4e41030d8b45d686b67485',
    messagingSenderId: '843652590816',
    projectId: 'flortiq-v2',
    storageBucket: 'flortiq-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGbpeP9rJRcdrxdbu39-1jmVXUKdHKMys',
    appId: '1:843652590816:ios:ea5007bb0828bfeeb67485',
    messagingSenderId: '843652590816',
    projectId: 'flortiq-v2',
    storageBucket: 'flortiq-v2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGbpeP9rJRcdrxdbu39-1jmVXUKdHKMys',
    appId: '1:843652590816:ios:ea5007bb0828bfeeb67485',
    messagingSenderId: '843652590816',
    projectId: 'flortiq-v2',
    storageBucket: 'flortiq-v2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC350Jvbji5Q5-nihjNS9hB4pgQq3loP_0',
    appId: '1:843652590816:web:8a9377f19ef3b000b67485',
    messagingSenderId: '843652590816',
    projectId: 'flortiq-v2',
    authDomain: 'flortiq-v2.firebaseapp.com',
    storageBucket: 'flortiq-v2.firebasestorage.app',
    measurementId: 'G-L7T3KQH4F7',
  );

}